### ISSUE TITLE
Plugin works in all file types

### ISSUE THREAD

**Issue by frazjp65** [glippi/lognroll-vim#1]
The plugin adds the maps regardless of the filetype. It is unlikely to be needed in anything other than JavaScript files.

**Comment by joeycozza** [comment]
It can also be useful in html, markdown, jsx files, typescript and more. Is there a convenient way to specify a handful of filetypes like this?

**Comment by glippi** [comment]
@frazjp65 I agree with you, as soon as I can I'll check out your PR.
@joeycozza you're right, it should work also on jsx, ts and tsx files. But maybe not in html and markdown

**Comment by glippi** [comment]
@frazjp65 Just merged your PR and add built on top of it some other small improvements.
@joeycozza  Now it should work only for `JavaScript`, `TypeScript`, `.jsx`, `.tsx` files.
